services:
  # Backend API service
  - type: web
    name: search-engine-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd backend && uvicorn app:app --host=0.0.0.0 --port=$PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATA_DIR
        value: ./data
      - key: PYTHONPATH
        value: /
      - key: MODEL_CACHE_TIME
        value: 3600

  # Frontend Streamlit service
  - type: web
    name: search-engine-frontend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: cd frontend && streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: API_URL
        fromService:
          type: web
          name: search-engine-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: STREAMLIT_SERVER_MAX_UPLOAD_SIZE
        value: 20
