services:
  # Backend API service
  - type: web
    name: search-engine-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: source .venv/bin/activate && cd backend && python -m uvicorn app:app --host=0.0.0.0 --port=$PORT --workers=1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATA_DIR
        value: ./data
      - key: PYTHONPATH
        value: /
      - key: TRANSFORMERS_CACHE
        value: ./backend/models/cache
      - key: MODEL_MAX_LENGTH
        value: 512

  # Frontend Streamlit service
  - type: web
    name: search-engine-frontend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements-deploy.txt
    startCommand: source .venv/bin/activate && cd frontend && streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: API_URL
        fromService:
          type: web
          name: search-engine-api
          envVarKey: RENDER_EXTERNAL_URL
